### ISSUE TITLE
Make command gets error for hipCaffe-first time install

### ISSUE THREAD

**Issue by dougzhang** [ROCmSoftwarePlatform/hipCaffe#18]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
Hi, I am new to rocm and hipcaffe.  Installed ROCM and installation verified and passed.  Installed hipcaffe according to https://github.com/ROCmSoftwarePlatform/hipCaffe/blob/hip/README.ROCm.md

And I get this after typing command Make:

dz@dz-ubuntu:~/hipCaffe$ make
make: hipconfig: Command not found
CXX src/caffe/data_reader.cpp
In file included from ./include/caffe/util/device_alternate.hpp:37:0,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hip/include/hip/hip_runtime.h:59:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^
In file included from /opt/rocm/hip/include/hip/hip_runtime.h:63:0,
                 from ./include/caffe/util/device_alternate.hpp:37,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hip/include/hip/hip_runtime_api.h:263:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^
In file included from /opt/rocm/hip/include/hip/hip_runtime.h:64:0,
                 from ./include/caffe/util/device_alternate.hpp:37,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hip/include/hip/hip_vector_types.h:38:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^
In file included from /opt/rocm/hipblas/include/hipblas.h:17:0,
                 from ./include/caffe/util/device_alternate.hpp:45,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hip/include/hip/hip_complex.h:33:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^
In file included from ./include/caffe/util/device_alternate.hpp:46:0,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hcrng/include/hiprng.h:74:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^
In file included from ./include/caffe/layers/data_layer.hpp:10:0,
                 from src/caffe/data_reader.cpp:8:
./include/caffe/layer.hpp:473:3: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
   long int CAFFE_DB = CAFFE_DB_str ? strtoul(CAFFE_DB_str, nullptr, 0) : 0x0;
   ^
In file included from /opt/rocm/hip/include/hip/hip_runtime.h:63:0,
                 from ./include/caffe/util/device_alternate.hpp:37,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hip/include/hip/hip_runtime_api.h:283:84: error: ‘hipHostMallocDefault’ was not declared in this scope
 static inline hipError_t hipHostMalloc( T** ptr, size_t size, unsigned int flags = hipHostMallocDefault)
                                                                                    ^
In file included from ./include/caffe/util/device_alternate.hpp:45:0,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/hipblas/include/hipblas.h:71:73: error: ‘hipStream_t’ has not been declared
 HIPBLAS_EXPORT hipblasStatus_t hipblasSetStream(hipblasHandle_t handle, hipStream_t streamId);
                                                                         ^
/opt/rocm/hipblas/include/hipblas.h:73:74: error: ‘hipStream_t’ has not been declared
 HIPBLAS_EXPORT hipblasStatus_t  hipblasGetStream(hipblasHandle_t handle, hipStream_t *streamId);
                                                                          ^
In file included from ./include/caffe/util/cudnn.hpp:6:0,
                 from ./include/caffe/util/device_alternate.hpp:48,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
/opt/rocm/include/miopen/miopen.h:76:9: error: ‘hipStream_t’ does not name a type
 typedef hipStream_t miopenAcceleratorQueue_t;
         ^
/opt/rocm/include/miopen/miopen.h:125:53: error: ‘miopenAcceleratorQueue_t’ has not been declared
                                                     miopenAcceleratorQueue_t stream);
                                                     ^
/opt/rocm/include/miopen/miopen.h:143:46: error: ‘miopenAcceleratorQueue_t’ has not been declared
                                              miopenAcceleratorQueue_t streamID);
                                              ^
/opt/rocm/include/miopen/miopen.h:153:46: error: ‘miopenAcceleratorQueue_t’ has not been declared
                                              miopenAcceleratorQueue_t* streamID);
                                              ^
In file included from ./include/caffe/common.hpp:19:0,
                 from src/caffe/data_reader.cpp:6:
./include/caffe/util/device_alternate.hpp: In function ‘int caffe::CAFFE_GET_BLOCKS(int)’:
./include/caffe/util/device_alternate.hpp:105:15: error: ‘CAFFE_HIP_NUM_THREADS’ was not declared in this scope
   return (N + CAFFE_HIP_NUM_THREADS - 1) / CAFFE_HIP_NUM_THREADS;
               ^
In file included from src/caffe/data_reader.cpp:6:0:
./include/caffe/common.hpp: At global scope:
./include/caffe/common.hpp:156:17: error: ‘hiprngGenerator_t’ does not name a type
   inline static hiprngGenerator_t hiprng_generator() {
                 ^
./include/caffe/common.hpp:190:3: error: ‘hiprngGenerator_t’ does not name a type
   hiprngGenerator_t hiprng_generator_;
   ^
In file included from ./include/caffe/common.hpp:19:0,
                 from src/caffe/data_reader.cpp:6:
./include/caffe/syncedmem.hpp: In function ‘void caffe::CaffeMallocHost(void**, size_t, bool*)’:
./include/caffe/util/device_alternate.hpp:61:80: error: ‘hipGetErrorString’ was not declared in this scope
           fprintf(stderr, "error: '%s'(%d) at %s:%d\n", hipGetErrorString(error), error,__FILE__, __LINE__); \
                                                                                ^
./include/caffe/syncedmem.hpp:19:7: note: in expansion of macro ‘HIP_CHECK’
       HIP_CHECK(hipHostMalloc(ptr, size));
       ^
./include/caffe/syncedmem.hpp: In function ‘void caffe::CaffeFreeHost(void*, bool)’:
./include/caffe/syncedmem.hpp:32:30: error: ‘hipHostFree’ was not declared in this scope
     HIP_CHECK(hipHostFree(ptr));
                              ^
./include/caffe/util/device_alternate.hpp:59:28: note: in definition of macro ‘HIP_CHECK’
        hipError_t error  = condition;\
                            ^
./include/caffe/util/device_alternate.hpp:61:80: error: ‘hipGetErrorString’ was not declared in this scope
           fprintf(stderr, "error: '%s'(%d) at %s:%d\n", hipGetErrorString(error), error,__FILE__, __LINE__); \
                                                                                ^
./include/caffe/syncedmem.hpp:32:5: note: in expansion of macro ‘HIP_CHECK’
     HIP_CHECK(hipHostFree(ptr));
     ^
In file included from ./include/caffe/blob.hpp:10:0,
                 from ./include/caffe/layers/data_layer.hpp:6,
                 from src/caffe/data_reader.cpp:8:
./include/caffe/syncedmem.hpp: At global scope:
./include/caffe/syncedmem.hpp:68:29: error: ‘hipStream_t’ does not name a type
   void async_gpu_push(const hipStream_t& stream);
                             ^
In file included from ./include/caffe/common.hpp:19:0,
                 from src/caffe/data_reader.cpp:6:
./include/caffe/util/math_functions.hpp: In function ‘void caffe::caffe_gpu_memset(size_t, int, void*)’:
./include/caffe/util/math_functions.hpp:178:34: error: ‘hipMemset’ was not declared in this scope
   HIP_CHECK(hipMemset(X, alpha, N));  // NOLINT(caffe/alt_fn)
                                  ^
./include/caffe/util/device_alternate.hpp:59:28: note: in definition of macro ‘HIP_CHECK’
        hipError_t error  = condition;\
                            ^
./include/caffe/util/device_alternate.hpp:61:80: error: ‘hipGetErrorString’ was not declared in this scope
           fprintf(stderr, "error: '%s'(%d) at %s:%d\n", hipGetErrorString(error), error,__FILE__, __LINE__); \
                                                                                ^
./include/caffe/util/math_functions.hpp:178:3: note: in expansion of macro ‘HIP_CHECK’
   HIP_CHECK(hipMemset(X, alpha, N));  // NOLINT(caffe/alt_fn)
   ^
In file included from ./include/caffe/layers/data_layer.hpp:10:0,
                 from src/caffe/data_reader.cpp:8:
./include/caffe/layer.hpp: In member function ‘Dtype caffe::Layer<Dtype>::Forward(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
./include/caffe/layer.hpp:471:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto mode = Caffe::mode();
   ^
./include/caffe/layer.hpp:471:8: error: ‘mode’ does not name a type
   auto mode = Caffe::mode();
        ^
./include/caffe/layer.hpp:473:60: error: ‘nullptr’ was not declared in this scope
   long int CAFFE_DB = CAFFE_DB_str ? strtoul(CAFFE_DB_str, nullptr, 0) : 0x0;
                                                            ^
./include/caffe/layer.hpp:480:12: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
       for (auto o=forceCpu.begin(); o!=forceCpu.end(); o++) {
            ^
./include/caffe/layer.hpp:480:17: error: ‘o’ does not name a type
       for (auto o=forceCpu.begin(); o!=forceCpu.end(); o++) {
                 ^
./include/caffe/layer.hpp:480:37: error: expected ‘;’ before ‘o’
       for (auto o=forceCpu.begin(); o!=forceCpu.end(); o++) {
                                     ^
./include/caffe/layer.hpp:480:37: error: ‘o’ was not declared in this scope
./include/caffe/layer.hpp:485:15: error: ‘mode’ was not declared in this scope
               mode = Caffe::CPU;
               ^
./include/caffe/layer.hpp:490:61: error: ‘mode’ was not declared in this scope
       printf ("run fwd layer %s mode=%s name=%s\n", type(), mode==Caffe::CPU ? "CPU" : "GPU", layer_param().name().c_str());
                                                             ^
./include/caffe/layer.hpp:493:11: error: ‘mode’ was not declared in this scope
   switch (mode) {
           ^
./include/caffe/layer.hpp: In member function ‘void caffe::Layer<Dtype>::Backward(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’:
./include/caffe/layer.hpp:540:60: error: ‘nullptr’ was not declared in this scope
   long int CAFFE_DB = CAFFE_DB_str ? strtoul(CAFFE_DB_str, nullptr, 0) : 0x0;
                                                            ^
./include/caffe/layer.hpp:542:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto mode = Caffe::mode();
   ^
./include/caffe/layer.hpp:542:8: error: ‘mode’ does not name a type
   auto mode = Caffe::mode();
        ^
./include/caffe/layer.hpp:547:12: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
       for (auto o=forceCpu.begin(); o!=forceCpu.end(); o++) {
            ^
./include/caffe/layer.hpp:547:17: error: ‘o’ does not name a type
       for (auto o=forceCpu.begin(); o!=forceCpu.end(); o++) {
                 ^
./include/caffe/layer.hpp:547:37: error: expected ‘;’ before ‘o’
       for (auto o=forceCpu.begin(); o!=forceCpu.end(); o++) {
                                     ^
./include/caffe/layer.hpp:547:37: error: ‘o’ was not declared in this scope
./include/caffe/layer.hpp:552:15: error: ‘mode’ was not declared in this scope
               mode = Caffe::CPU;
               ^
./include/caffe/layer.hpp:557:61: error: ‘mode’ was not declared in this scope
       printf ("run bwd layer %s mode=%s name=%s\n", type(), mode==Caffe::CPU ? "CPU" : "GPU", layer_param().name().c_str());
                                                             ^
./include/caffe/layer.hpp:560:11: error: ‘mode’ was not declared in this scope
   switch (mode) {
           ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
Makefile:628: recipe for target '.build_release/src/caffe/data_reader.o' failed
make: *** [.build_release/src/caffe/data_reader.o] Error 1
dz@dz-ubuntu:~/hipCaffe$ 

Any help would be much appreciated.

Doug

### Your system configuration
Ryzen Threadripper 1900x
Rx Vega FE
Operating system: Ubuntu 16.0.4.2
Compiler: 
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by parallelo** [comment]
Hi @dougzhang.  

Looking at your log, this is the important line:  
```
make: hipconfig: Command not found
```

This command is critical because it is used to determine the platform type (ROCm vs CUDA).  

Can you please check whether `hipconfig` is in your path?  

```
which hipconfig
```

If it is not, then do this: 
```
echo 'export PATH=/opt/rocm/bin:$PATH' >> $HOME/.bashrc
source $HOME/.bashrc
```
Additionally, I'll update the README to better document this.  

Thanks, 

Jeff

**Comment by dougzhang** [comment]
Thanks, Jeff!  hipconfig was not in the path.  Fixed it with the lines; it is working great now.  (yes, please do include this in the README; others might run into this)
