### ISSUE TITLE
Segmentation Fault when re-run train job which interrupted previsouly

### ISSUE THREAD

**Issue by dhzhd1** [ROCmSoftwarePlatform/hipCaffe#20]
### Issue summary
I am not sure if this a problem. I training ImageNet on VGG-16 network with multiple GPUs (MI25 x 4). After interrupted current training job, and re-run this training again, caffe shows below error message. But if I change the training command to use any single GPU in my system, no error found.  
The workaround env "export HCC_UNPINNED_COPY_MODE=2" has been applied before training. 

Error Message:
*** Aborted at 1509489472 (unix time) try "date -d @1509489472" if you are using GNU date ***
PC: @     0x7f36ae941faa (unknown)
*** SIGSEGV (@0x15b475060) received by PID 8045 (TID 0x7ef26b7fe700) from PID 1531400288; stack trace: ***
    @     0x7f36b4a1c390 (unknown)
    @     0x7f36ae941faa (unknown)
    @     0x7f36b34b1315 Mrg32k3aCreateStream()
    @     0x7f36b34b1235 hcrngMrg32k3aCreateOverStreams()
    @     0x7f36b352943f hiprngSetPseudoRandomGeneratorSeed
    @           0x522ffc caffe::Caffe::SetDevice()
    @           0x722dca caffe::P2PSync<>::InternalThreadEntry()
    @     0x7f36b0eb15d5 (unknown)
    @     0x7f36b4a126ba start_thread
    @     0x7f36ae8fb3dd clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

### Steps to reproduce
1. Run the below command to train my network
amax@p47:/data/ImageNet/imagenet$ /home/amax/hipCaffe/build/tools/caffe train -solver=/data/ImageNet/models/vgg_net/vgg_solver.prototxt -gpu 0,1,2,3
2. Use Ctrl-C to interrupt this job
3. Re-Run the command in the step 1. It will show the error message above.
4. If I change the '-gpu' to any single gpu, the program will run but only one GPU.
5. If I change the '-gpu' to any number of gpu, the program still show above error message. But during my testing, there still 1/10 chance to run without error message.
6. This error message also happened when I run the train job when the system just boot up.
7. After waiting several minutes, some times the job could be run again but some times not.

I am not sure the root cause, from the error message it seems the device resource has not be released after the previous job terminated.

### Your system configuration
Operating system: Ubuntu 16.04.3
Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:    USE_ROCBLAS := 1
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7.12
Other:
       miopen-hip 1.1.4 
       miopengemm 1.1.5
       rocm-libs 1.6.180
Server:  Inventec P47
GPU: AMD MI25 x4 
CPU: AMD EPYC 7601 x2
Memory: 512GB

**Comment by parallelo** [comment]
Hi @dhzhd1, 

We should have a solution for this `hiprngSetPseudoRandomGeneratorSeed` issue.  The fix uses a new RNG lib.  Let me gather those details and I'll send them your way.  

Follow-up question:  do you use docker?  

Best, 

Jeff

**Comment by dhzhd1** [comment]
Hi @parallelo , 
No, current I just testing hipCaffe on physical server.

**Comment by parallelo** [comment]
Okay, I'll have some details for you by tomorrow.

**Comment by parallelo** [comment]
All set.  Had to take my kid to celebrate tonight's festivities  :jack_o_lantern: :ghost: :jack_o_lantern:
___
To avoid the error you reported, we need to use `rocRAND` in place of `hcRNG`.   `rocRAND` is similar in that it implements a random number generator using the HIP interface to ROCm.  

Assuming you've already got a valid ROCm 1.6.4 installation, let's start with this:  
```
# Install rocRAND
cd /tmp
git clone https://github.com/ROCmSoftwarePlatform/rocRAND.git
cd rocRAND && mkdir build && cd build
cmake .. && make -j$(nproc) && make package
sudo dpkg -i ./rocrand*.deb

# Grab hipCaffe's rocRAND changes and rebuild
cd $CAFFE_ROOT
git checkout -b rocrand origin/rocrand
cp ./Makefile.config.example ./Makefile.config
make clean && make -j$(nproc)
```

Then, verify you're using rocRAND:  
```
ldd build/tools/caffe | grep -iE 'rng|rand'
``` 

You should see `*rand` libraries but no `*rng` libraries:  
```	
libhiprand.so.1 => /opt/rocm/hiprand/lib/libhiprand.so.1 (0x00007fd773bbc000)
librocrand.so.1 => /opt/rocm/rocrand/lib/librocrand.so.1 (0x00007fd773101000)
```

After, check some of the workloads in the [Quickstart Guide](https://rocm.github.io/ROCmHipCaffeQuickstart.html).  If those tests look reasonable, move on to your multi-GPU workload.  

Please let us know how it goes.

**Comment by dhzhd1** [comment]
Hi Jeff, 
Thanks for your guide. Let me verify it tomorrow. I am with my kid for candy hunting too.  ;)
Happy Halloween!

**Comment by dhzhd1** [comment]
@parallelo Thanks for your instruction. It is running well now.

**Comment by parallelo** [comment]
Very happy to hear it.  Keep us posted with your results.
