### ISSUE TITLE
Error building hipCaffe

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/hipCaffe#22]
I followed the instruction but I'm getting this error when building hipCaffe.

> .build_release/src/caffe/proto/caffe.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^

Clean set up of Ubuntu 16.04.3 and ROCm-1.6-180.
Any advice?

**Comment by parallelo** [comment]
Hi @briansp2020, 

Maybe you have multiple versions of protoc / protobuf on your system?  

Looks like folks have seen similar issues on the standard version (`bvlc/caffe`) too.  Here are some examples of solutions:  

https://github.com/BVLC/caffe/issues/5645
https://github.com/BVLC/caffe/issues/4512

Keep us posted on how this goes.  

Best, 

Jeff

**Comment by briansp2020** [comment]
@parallelo 
Uninstalling Protobuf from Anaconda did the trick.
Thanks for the pointer.

I have another question if you don't mind. Is there a guide for configuring keras & tensorflow that uses ROCm? I'm going through Fast.ai classes and it is extremely slow training just using my CPU (Ryzen 7 1800X). I want to try using my GPU (Fury Nano) and see if that is any faster.

Thanks again for your help.

**Comment by sunway513** [comment]
@shuaiche , can you help comment on Keras on ROCm?
We have hipTF released:
https://github.com/ROCmSoftwarePlatform/hiptensorflow

**Comment by briansp2020** [comment]
Thanks for the help. I was able to get Keras to work with hipTF.
http://briansp2020.github.io/2017/11/05/fast_ai_ROCm/
