### ISSUE TITLE
hcRNG

### ISSUE THREAD

**Issue by msabony1966** [ROCmSoftwarePlatform/hipCaffe#27]
please add hRNG instelation to the README file
Thanks
Mazda

**Comment by parallelo** [comment]
Hi Mazda - With 1.7, we started using 'rocRAND' instead of 'hcRNG' -- this fixes some stability issues.  You'll need to use the 'rocrand' branch of hipCaffe to use the correct API calls.  Please see the README.ROCm.md for further details.  Thanks!
