### ISSUE TITLE
Everything fails, hardcoded jenkins paths in binaries

### ISSUE THREAD

**Issue by ghost** [ROCmSoftwarePlatform/hipCaffe#3]
If I follow the ROCm readme to the letter, I end up successfully building everything, but tests don't run:

```bash
$ ./build/test/test_all.testbin
### HCC RUNTIME ERROR: Fail to find compatible kernel at file:/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/external/hcc-tot/lib/mcwamp.cpp line:344
```

This is aside from my other problem, which is that installing ROCm completely destabilised my Ubuntu install, and on a fresh reinstall of 16.04 it stops any GUI from appearing, so I'm working from TTY1.. When will ROCm work with a real kernel?

**Comment by bensander** [comment]
Hi- let's back up and validate your rocm install.
Does your system meet the requirements :
https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md

If so, can you run the sample from here:

https://github.com/RadeonOpenCompute/ROCR-Runtime/tree/master/sample

On May 20, 2017, at 2:31 PM, Cathal Garvey <notifications@github.com<mailto:notifications@github.com>> wrote:


If I follow the ROCm readme to the letter, I end up successfully building everything, but tests don't run:

$ ./build/test/test_all.testbin
### HCC RUNTIME ERROR: Fail to find compatible kernel at file:/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/external/hcc-tot/lib/mcwamp.cpp line:344

This is aside from my other problem, which is that installing ROCm completely destabilised my Ubuntu install, and on a fresh reinstall of 16.04 it stops any GUI from appearing, so I'm working from TTY1.. When will ROCm work with a real kernel?

**Comment by ghost** [comment]
Hey! Yep, I'm running with an R9 390 and an i5. I have to `export HCC_AMDGPU_TARGET=gfx701`, but the test program does build and run/execute correctly.

The error I'm getting from hipCaffe really looks unrelated to my setup though, this looks like a bad build/test config somewhere.

Though,  I would also love some feedback on how to make this not-crash my computer all the time. :)

I now note that if I leave TTY1 open long enough, some errs start printing about failed atomic checks. I'm aware the r9 series can't do some atomic instructions used by ROCm, but the GFX701 line are supposed to be supported anyway?

Should I be rebuilding the entire ROCm project for my GPU using the target variable, above? Might that account for the instability? If so I'll just bow out and wait for this to mature..
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghost** [comment]
Using different hardware, this now works; I get the same test results as #2. It may have reflected an underlying support issue with the card I was using, though it's still a mystery to me why it ended up referring to Jenkins-related paths.. :)
