### ISSUE TITLE
HCC RUNTIME ERROR:

### ISSUE THREAD

**Issue by haozhangcn** [ROCmSoftwarePlatform/hipCaffe#39]
### Issue summary
./build/test/test_all.testbin

Backtrace:
0x00007f04870cd32e:	Kalmar::CLAMP::DetermineAndGetProgram(Kalmar::KalmarQueue*, unsigned long*, void**) + 0x59e
0x00007f04870cd690:	Kalmar::KalmarBootstrap::KalmarBootstrap() + 0x120
0x00007f04870cd549:	__hcc_shared_library_init + 0x29
0x00007f048a2766ba:	_dl_rtld_di_serinfo + 0x706a
0x00007f048a2767cb:	_dl_rtld_di_serinfo + 0x717b
0x00007f048a266c6a:	<unknown function> + 0x717b

### Your system configuration
Operating system: Ubuntu 16.04
Compiler:
hipCaffe

**Comment by parallelo** [comment]
Hi @MAXHAOZHANG, 

Thanks for the error report.  

Can you check which version of `hcc` you have?  
```
dpkg -l | grep hcc
```

When did you last install and/or update ROCm?  

Thanks, 

Jeff

**Comment by haozhangcn** [comment]
The GPU in my server does not support ROCm -v1.7 -- From AMD
AMD Firepro W9100

Thank you!
