### ISSUE TITLE
Build instructions suggest rocrand branch, which requires (missing) cxlativitylogger

### ISSUE THREAD

**Issue by davclark** [ROCmSoftwarePlatform/hipCaffe#40]
### Issue summary

Following the build instructions in the README fails, because cxlactivitylogger is not installed. See also:

https://github.com/RadeonOpenCompute/ROCm/issues/327

### Steps to reproduce

Follow instructions on the README verbatim, you get errors like:

    /opt/rocm/include/hip/hip_profile.h:31:10: fatal error: 'CXLActivityLogger.h' file not found

### Your system configuration
Operating system: Ubuntu 16.04.3
Compiler: HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang ac8732c272d3ce6a4d1ee6aa636f06d44cd5170c) (ssh://gerritgit/compute/ec/hcc-tot/llvm 710f135c41925e12aa088c26e1a9f583b1778fbe) (based on HCC 1.2.18063-7e18c64-ac8732c-710f135 )

**Comment by davclark** [comment]
Actually, I see this was fixed in 8a3f35b276772b672cf3ce729b2f0e29e1715005. So, there's still a documentation fix, but just tell users to use the `hip` branch instead of `rocrand` (which is what README.ROCm.md currently says)

**Comment by sunway513** [comment]
Updated with commit a70e8e05bf9010eaf08f61757d1b54849b25ef96, thanks for pointing it out.
