### ISSUE TITLE
Having Same problem with #3

### ISSUE THREAD

**Issue by hanbin973** [ROCmSoftwarePlatform/hipCaffe#7]
I'm using RX480 with Haswell Xeon 1231v3.
I'm having the same problem with #3 with ROCm 1.6 installed from the AMD repo.

**Comment by hanbin973** [comment]
The error message is almost idential
`Backtrace:
0x00007f75f14ffa71:	Kalmar::CLAMP::DetermineAndGetProgram(Kalmar::KalmarQueue*, unsigned long*, void**) + 0x571
0x00007f75f14ffd80:	Kalmar::KalmarBootstrap::KalmarBootstrap() + 0x120
0x00007f75f14ffc39:	__hcc_shared_library_init + 0x29
0x00007f75f45fc6ba:	_dl_rtld_di_serinfo + 0x706a
0x00007f75f45fc7cb:	_dl_rtld_di_serinfo + 0x717b
0x00007f75f45ecc6a:	<unknown function> + 0x717b

### HCC RUNTIME ERROR: Fail to find compatible kernel at file:/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.6/external/hcc-tot/lib/mcwamp.cpp line:346
`

**Comment by hanbin973** [comment]
I tested on other applications and it seems to have the same error.
I compiled hcFFT and ran the test getting the following result
`Backtrace:
0x00007feb0c7cbd11:	Kalmar::CLAMP::DetermineAndGetProgram(Kalmar::KalmarQueue*, unsigned long*, void**) + 0x571
0x00007feb0c7cc020:	Kalmar::KalmarBootstrap::KalmarBootstrap() + 0x120
0x00007feb0c7cbed9:	__hcc_shared_library_init + 0x29
0x00007feb0d48a6ba:	_dl_rtld_di_serinfo + 0x706a
0x00007feb0d48a7cb:	_dl_rtld_di_serinfo + 0x717b
0x00007feb0d47ac6a:	<unknown function> + 0x717b

### HCC RUNTIME ERROR: Fail to find compatible kernel at file:/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.6/external/hcc-tot/lib/mcwamp.cpp line:346
`

**Comment by parallelo** [comment]
Hi!  Thanks for the heads-up.  We're in the process of updating some of our 1.6 libs.  Please stay tuned.

**Comment by hanbin973** [comment]
I've tried compiling hcFFT and hipCaffe several times but stil getting the same error.
However, when I compile a simple test file in the rocm git (namely saxpy.cpp) it actually works without any error. 
I've also tested hipEigen and got positive results. 'make check' just works without no errors.

**Comment by parallelo** [comment]
Yes, I believe this is a target arch issue with a few of our library packages.  Updates coming soon.

**Comment by parallelo** [comment]
@SNUmed - Quick update:  now just waiting for our repo server to get updated with the correct packages.  Should be ready pretty soon.

**Comment by hanbin973** [comment]
Thank you for the notification.
I tired after updating all the libraries and it seems to work well.
I tried a Mnist test and got impressive results.
` real 0m59.638s
user 0m40.488s
sys 0m2.608s`
Comparing to the Titan X(not sure which titan though), it is still faster!

**Comment by gstoner** [comment]
@SNUmed Thank you for the update  and your patience as we addressed the library build issue.
