### ISSUE TITLE
test_all fails at InternalThreadTest.TestRandomSeed

### ISSUE THREAD

**Issue by ptsant** [ROCmSoftwarePlatform/hipCaffe#8]
### Issue summary
test_all.testbin fais at the following test. All preceding tests are OK:
```
[----------] 2 tests from InternalThreadTest
[ RUN      ] InternalThreadTest.TestStartAndExit
[       OK ] InternalThreadTest.TestStartAndExit (14 ms)
[ RUN      ] InternalThreadTest.TestRandomSeed
*** Aborted at 1499717161 (unix time) try "date -d @1499717161" if you are using GNU date ***
PC: @     0x7f4a6bb45116 (unknown)
*** SIGSEGV (@0x0) received by PID 7887 (TID 0x7f4a719e2b80) from PID 0; stack trace: ***
    @     0x7f4a70ea0390 (unknown)
    @     0x7f4a6bb45116 (unknown)
    @     0x7f4a4f35d75d HSACopy::syncCopyExt()
    @     0x7f4a4f35c8bc Kalmar::HSAQueue::copy_ext()
    @     0x7f4a715daa5b ihipStream_t::locked_copySync()
    @     0x7f4a716020bf hipMemcpy
    @     0x7f4a6f9da4f8 hiprngSetPseudoRandomGeneratorSeed
    @           0xc41b60 caffe::Caffe::set_random_seed()
    @           0x48827b caffe::InternalThreadTest_TestRandomSeed_Test::TestBody()
    @           0xb47884 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xb47745 testing::Test::Run()
    @           0xb488f0 testing::TestInfo::Run()
    @           0xb49137 testing::TestCase::Run()
    @           0xb4f517 testing::internal::UnitTestImpl::RunAllTests()
    @           0xb4ef64 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xb4ef19 testing::UnitTest::Run()
    @           0xf83cda main
    @     0x7f4a6ba17830 __libc_start_main
    @           0xf76c19 _start
    @                0x0 (unknown)
```

### Steps to reproduce

Freshly compiled hipCaffe with default Makefile.config. Compilation flags = -O3
I am using the latest ROCm from debian packages. Running the MNIST lenet example works fine (with or without MIOpen). 

### Your system configuration
Operating system: Linux Mint 18 (Debian derivative)
Compiler: GCC v5.4.0, HCC clang 5.0
CUDA version (if applicable): not applicable
CUDNN version (if applicable): not applicable
BLAS: ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively): not applicable

**Comment by parallelo** [comment]
Thanks for the heads-up, @ptsant .  We'll take a look.

**Comment by parallelo** [comment]
Hello @ptsant, 

Got a chance to dig a little deeper on this today.  It looks to be a hcRNG regression.  We'll report this to the hcRNG folks, and when there's a fix, then we'll update our rocm-libs / hcrng packages in the 1.6 repo.  

In the meantime, I can provide a workaround for this issue by dropping back to an earlier hcRNG commit.  Let me do a git-bisect to get the specific last-known-working commit, and then I'll send the workaround instructions.  

Thanks again for reporting the issue and for your patience while we get it resolved.  

Best, 

Jeff

**Comment by parallelo** [comment]
Here's the workaround, @ptsant.  We're just grabbing an earlier commit from hcRNG and re-installing it.  
```
# Revert to a specific hcRNG commit (before the regression)
git clone https://github.com/ROCmSoftwarePlatform/hcRNG.git
cd hcRNG
git checkout -b seed-workaround c246faa3426da76c9fa354f52b0864c50182b78d

# Re-build and re-install it
./clean.sh
./build.sh
sudo dpkg -i ./build/hcrng-*Linux.deb

# Re-test
cd ~/hipCaffe
./build/test/test_all.testbin --gtest_filter=InternalThreadTest.TestRandomSeed
```
And the results look good once again:  
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from InternalThreadTest
[ RUN      ] InternalThreadTest.TestRandomSeed
[       OK ] InternalThreadTest.TestRandomSeed (3 ms)
[----------] 1 test from InternalThreadTest (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3 ms total)
[  PASSED  ] 1 test.
```

**Comment by ptsant** [comment]
Thanks a lot for fixing it so quickly, it worked!

I would also like to say that I'm impressed with the performance of hipCaffe vs the OpenCL branch. Great job.
