### ISSUE TITLE
Problem with lenet on GPU

### ISSUE THREAD

**Issue by BeamOfLight** [ROCmSoftwarePlatform/hipCaffe#9]
### Issue summary

I have a problem with lenet.prototxt. 
./caffe time -model '../../examples/mnist/lenet.prototxt' - OK
./caffe time -model '../../examples/mnist/lenet.prototxt' -gpu 0 - fails with this message:

```
Network initialization done.
I0714 10:10:04.648849 13230 caffe.cpp:355] Performing Forward
terminate called after throwing an instance of 'char const*'
*** Aborted at 1500016205 (unix time) try "date -d @1500016205" if you are using GNU date ***
PC: @     0x7f76dc314428 gsignal
*** SIGABRT (@0x3e8000033ae) received by PID 13230 (TID 0x7f76e4675b00) from PID 13230; stack trace: ***
    @     0x7f76e3b0a390 (unknown)
    @     0x7f76dc314428 gsignal
    @     0x7f76dc31602a abort
    @     0x7f76e295970d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f76e294f4b6 __cxxabiv1::__terminate()
    @     0x7f76e294f501 std::terminate()
    @     0x7f76e294f609 __cxa_throw
    @     0x7f76e294dddc hipblasSgemm
    @           0x6b9449 caffe::caffe_gpu_gemm<>()
    @           0x654ec4 caffe::InnerProductLayer<>::Forward_gpu()
    @           0x430b2f caffe::Layer<>::Forward()
    @           0x6ff4d7 caffe::Net<>::ForwardFromTo()
    @           0x6ff3ef caffe::Net<>::Forward()
    @           0x42fa5e time()
    @           0x431412 main
    @     0x7f76dc2ff830 __libc_start_main
    @           0x850cf9 _start
    @                0x0 (unknown)
```

### Steps to reproduce

Freshly compiled hipCaffe with default Makefile.config. Compilation flags = -O3
I am using the latest ROCm from debian packages. Running the MNIST lenet example works fine only with CPU. 
test_all.testbin show problems with other networks with GPU.

### Your system configuration

Operating system: Ubuntu 16.04.2 LTS with 4.9.0-kfd-compute-rocm-rel-1.6-77
Compiler: GCC v5.4.0, HCC clang 5.0
CUDA version (if applicable): not applicable
CUDNN version (if applicable): not applicable
BLAS: ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively): not applicable

Hardware: Radeon Pro WX 7100

**Comment by BeamOfLight** [comment]
Logs here: [test_all_testbin.txt](https://github.com/ROCmSoftwarePlatform/hipCaffe/files/1147822/test_all_testbin.txt)

**Comment by parallelo** [comment]
@BeamOfLight - Thanks for giving us a heads-up.  We'll take a look.

**Comment by parallelo** [comment]
Hi @BeamOfLight, 

On my side, I'm not able to reproduce the failure using ROCm 1.6 -- I can run both the LeNet 'caffe time' example and the GemmTest.  

```
# ./build/test/test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU
Cuda number of devices: 1
Current device id: 0
Current device name: Device 67df
Note: Google Test filter = GemmTest/0.TestGemmCPUGPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GemmTest/0, where TypeParam = float
[ RUN      ] GemmTest/0.TestGemmCPUGPU
[       OK ] GemmTest/0.TestGemmCPUGPU (5 ms)
[----------] 1 test from GemmTest/0 (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 1 test.
```

Seems like a good place to start is with your BLAS lib.  Can you please confirm that you have rocm-libs (and rocblas) deb packages installed?  

```
# dpkg -l | grep -E 'rocm-libs|rocblas'
ii  rocblas                                0.5.2.0                            amd64        Radeon Open Compute BLAS library
ii  rocm-libs                              1.6.77                             amd64        Radeon Open Compute (ROCm) Runtime software stack
```

And also, please confirm whether you can run this specific test (seems like a good reduced test case considering your log file showed that this test failed):  
```
./build/test/test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU
```

**Comment by parallelo** [comment]
And one more test (just to confirm your ROCm / HIP install is okay):  
```
cd /opt/rocm/hip/samples/0_Intro/square/
sudo make
./square.hip.out 
```
You should see output similar to this:  
```
info: running on device Device 67df
info: architecture on AMD GPU device is: 803
info: allocate host mem (  7.63 MB)
info: allocate device mem (  7.63 MB)
info: copy Host2Device
info: launch 'vector_square' kernel
info: copy Device2Host
info: check result
PASSED!
```

**Comment by BeamOfLight** [comment]
```
info: running on device Device 67c4
info: architecture on AMD GPU device is: 803
info: allocate host mem (  7.63 MB)
info: allocate device mem (  7.63 MB)
info: copy Host2Device
info: launch 'vector_square' kernel
info: copy Device2Host
info: check result
PASSED!

```

**Comment by BeamOfLight** [comment]
About BLAS libs:
```
$  dpkg -l | grep -E 'rocm-libs|rocblas'
ii  rocblas                                         0.5.2.0                                        amd64        Radeon Open Compute BLAS library
ii  rocm-libs                                       1.6.77                                         amd64        Radeon Open Compute (ROCm) Runtime software stack

```

And about specific test:
```
$ ./test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU
Cuda number of devices: 1
Current device id: 0
Current device name: Device 67c4
Note: Google Test filter = GemmTest/0.TestGemmCPUGPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GemmTest/0, where TypeParam = float
[ RUN      ] GemmTest/0.TestGemmCPUGPU
*** Aborted at 1500046315 (unix time) try "date -d @1500046315" if you are using GNU date ***
PC: @           0x435945 caffe::Blob<>::~Blob()
*** SIGSEGV (@0x60000000e) received by PID 27569 (TID 0x7f56f9723b00) from PID 14; stack trace: ***
    @     0x7f56f8bb8390 (unknown)
    @           0x435945 caffe::Blob<>::~Blob()
    @           0x5a5b5e caffe::GemmTest_TestGemmCPUGPU_Test<>::TestBody()
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

**Comment by parallelo** [comment]
Okay, let's run some rocBLAS examples to make sure that lib is working correctly.  

Can you follow these quick & easy rocBLAS build/test instructions?  "Single command to download, configure, build, install":  https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Build-rocBLAS-libraries-and-verification-code#single-command-to-download-configure-build-install

Here's the verbose output from the sscal example (showing memcopies and a kernel launch):   
```
# HIP_TRACE_API=0x5 ./example-sscal
HIP_DB=0x1 [api]
  hip-api tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7feb664f8800)
<<hip-api tid:1.1 hipGetDevice (0x1d56ef0)
  hip-api tid:1.1 hipGetDevice                   ret= 0 (hipSuccess)>>
<<hip-api tid:1.2 hipGetDeviceProperties (0x1d56ef8, 0)
  hip-api tid:1.2 hipGetDeviceProperties         ret= 0 (hipSuccess)>>
<<hip-api tid:1.3 hipMalloc (0x7ffea19b4448, 40960)
  hip-api tid:1.3 hipMalloc                      ret= 0 (hipSuccess)>>
<<hip-api tid:1.4 hipMemcpy (0x90211d000, 0x7feb5c127830, 40960, hipMemcpyHostToDevice)
  hip-api tid:1.4 hipMemcpy                      ret= 0 (hipSuccess)>>
N        rocblas(us)     
<<hip-api tid:1.5 hipDeviceSynchronize ()
  hip-api tid:1.5 hipDeviceSynchronize           ret= 0 (hipSuccess)>>
<<hip-api tid:1.6 hipPointerGetAttributes (0x7ffea19b4370, 0x7ffea19b4444)
  hip-api tid:1.6 hipPointerGetAttributes        ret=1030 (hipErrorUnknown)>>
1.6 hipLaunchKernel '(scal_kernel_host_scalar)' gridDim:{40,1,1} groupDim:{256,1,1} sharedMem:+0 stream:0.0
<<hip-api tid:1.7 hipDeviceSynchronize ()
  hip-api tid:1.7 hipDeviceSynchronize           ret= 0 (hipSuccess)>>
<<hip-api tid:1.8 hipMemcpy (0x7feb5c127830, 0x90211d000, 40960, hipMemcpyDeviceToHost)
  hip-api tid:1.8 hipMemcpy                      ret= 0 (hipSuccess)>>
10240      138.00        
<<hip-api tid:1.9 hipFree (0x90211d000)
  hip-api tid:1.9 hipFree                        ret= 0 (hipSuccess)>>
````

**Comment by parallelo** [comment]
@BeamOfLight - A few more questions for you:  

- Did you previously install 'hcBLAS' and later install 'rocBLAS'?  (currently hipCaffe is using rocBLAS instead of hcBLAS -- if both are installed, maybe there's some sort of unexpected conflict)

- Can you please provide the output from this command? :  
```
cd hipCaffe
ldd ./build/tools/caffe | grep -i blas
```

You should see libhipblas and librocblas in the output.

**Comment by BeamOfLight** [comment]
For installation i use this command:
`sudo apt-get install rocm rocm-opencl-dev hsa-rocr-dev hsa-ext-rocr-dev hsakmt-roct-dev miopengemm miopen-hip rocm-libs hcblas hcrng hcfft hip_hcc hip_base hip_doc hcc cxlactivitylogger rocm-profiler rocm-utils`


Output for "ldd ./build/tools/caffe | grep -i blas" command:

> libhipblas-hcc.so.1 => /usr/lib/libhipblas-hcc.so.1 (0x00007f183dd0f000)
> libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f18381c6000)
> librocblas-hcc.so.1 => /usr/lib/librocblas-hcc.so.1 (0x00007f18330ae000)

**Comment by BeamOfLight** [comment]
> Okay, let's run some rocBLAS examples to make sure that lib is working correctly.
> 
> Can you follow these quick & easy rocBLAS build/test instructions? "Single command to download, configure, build, install": https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Build-rocBLAS-libraries-and-verification-code#single-command-to-download-configure-build-install

After these commands:
```
mkdir -p ~/repos && cd ~/repos && \
git clone -b master https://github.com/ROCmSoftwarePlatform/rocBLAS.git && \
mkdir -p ~/repos/rocBLAS/build && cd ~/repos/rocBLAS/build && \
cmake .. -DBUILD_SHARED_LIBS=ON \
-DCMAKE_PREFIX_PATH=~/repos/rocBLAS/build/library-package \
-DCPACK_PACKAGING_INSTALL_PREFIX=/opt/rocm/rocblas \
-DHIP_ROOT=/opt/rocm/hip && \
make -j`nproc`

cd ~/repos/rocBLAS/build/clients-build/samples-build
```

I have this result:
```
HIP_TRACE_API=0x5 ./example-sscal
HIP_DB=0x1 [api]
  hip-api tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7fd15f503800)
<<hip-api tid:1.1 hipGetDevice (0x1b12ec0)
  hip-api tid:1.1 hipGetDevice                   ret= 0 (hipSuccess)>>
<<hip-api tid:1.2 hipGetDeviceProperties (0x1b12ec8, 0)
  hip-api tid:1.2 hipGetDeviceProperties         ret= 0 (hipSuccess)>>
<<hip-api tid:1.3 hipMalloc (0x7ffe4d7523e8, 40960)
  hip-api tid:1.3 hipMalloc                      ret= 0 (hipSuccess)>>
<<hip-api tid:1.4 hipMemcpy (0x901f9d000, 0x1b1ee60, 40960, hipMemcpyHostToDevice)
  hip-api tid:1.4 hipMemcpy                      ret= 0 (hipSuccess)>>
N        rocblas(us)     
<<hip-api tid:1.5 hipDeviceSynchronize ()
  hip-api tid:1.5 hipDeviceSynchronize           ret= 0 (hipSuccess)>>
<<hip-api tid:1.6 hipPointerGetAttributes (0x7ffe4d752310, 0x7ffe4d7523e4)
  hip-api tid:1.6 hipPointerGetAttributes        ret=1030 (hipErrorUnknown)>>
1.6 hipLaunchKernel '(scal_kernel_host_scalar)' gridDim:{40,1,1} groupDim:{256,1,1} sharedMem:+0 stream:0.0
<<hip-api tid:1.7 hipDeviceSynchronize ()
  hip-api tid:1.7 hipDeviceSynchronize           ret= 0 (hipSuccess)>>
<<hip-api tid:1.8 hipMemcpy (0x1b1ee60, 0x901f9d000, 40960, hipMemcpyDeviceToHost)
  hip-api tid:1.8 hipMemcpy                      ret= 0 (hipSuccess)>>
10240      123.00        
<<hip-api tid:1.9 hipFree (0x901f9d000)
  hip-api tid:1.9 hipFree                        ret= 0 (hipSuccess)>>

```

**Comment by parallelo** [comment]
Hello @BeamOfLight, 

Thanks for the extra details.  Trying to figure out why we can't reproduce this issue.  

Can you please uninstall everything related to ROCm (especially hcBLAS), and _exactly_ follow the current hipCaffe install instructions?  :  https://github.com/ROCmSoftwarePlatform/hipCaffe/blob/hip/README.ROCm.md

Looks like you are installing hcBLAS (which is not included in the hipCaffe instructions), and maybe it is unexpectedly conflicting with our rocBLAS implementation.  

Then, rerun our simple test:  
```
./build/test/test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU
```

Thanks, 

Jeff

**Comment by parallelo** [comment]
Also, if that same error persists with TestGemmCPUGPU, can you please do a debug build of Caffe and get a back trace of the segfault?  

Something like this: 
```
cd hipCaffe
sed -i 's/# DEBUG := 1/DEBUG := 1/g' ./Makefile.config
make clean
make -j$(nproc) && make test -j$(nproc)
gdb --args ./build/test/test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU
[inside gdb...]
run
backtrace
```

Thanks, 

Jeff

**Comment by BeamOfLight** [comment]
After these actions:
1. Removing ROCm https://github.com/RadeonOpenCompute/ROCm#removing-pre-release-packages
2. Reinstallation drivers for videocard: http://support.amd.com/en-us/download/workstation?os=Linux+x86_64#
3. ROCm installation: https://github.com/ROCmSoftwarePlatform/hipCaffe/blob/hip/README.ROCm.md
I have these results:
```
1. $ ./build/test/test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU
Cuda number of devices: 1
Current device id: 0
Current device name: Device 67c4
Note: Google Test filter = GemmTest/0.TestGemmCPUGPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GemmTest/0, where TypeParam = float
[ RUN      ] GemmTest/0.TestGemmCPUGPU
[       OK ] GemmTest/0.TestGemmCPUGPU (5 ms)
[----------] 1 test from GemmTest/0 (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 1 test.
```

2. After command `./caffe time -model '../../examples/mnist/lenet.prototxt' -gpu 0`
```
...
I0718 19:41:14.390725 23542 caffe.cpp:412] Average Forward pass: 1.12112 ms.
I0718 19:41:14.390729 23542 caffe.cpp:414] Average Backward pass: 8.52961 ms.
I0718 19:41:14.390733 23542 caffe.cpp:416] Average Forward-Backward: 9.70158 ms.
I0718 19:41:14.390738 23542 caffe.cpp:418] Total Time: 485.079 ms.
I0718 19:41:14.390743 23542 caffe.cpp:419] *** Benchmark ends ***

```
It's ok, but i have a new problem - long tests (for CPU and GPU i have same times) like this:
```
[ RUN      ] TileLayerTest/1.TestGradientNum
[       OK ] TileLayerTest/1.TestGradientNum (311653 ms)
```

**Comment by parallelo** [comment]
@BeamOfLight - Glad you were able to successfully run LeNet.  

However, your extra "Re-installation of Drivers" step is not necessary -- let's try to simplify your setup as much as possible, so we don't run into any unexpected issues later.  You'll want to uninstall those other drivers, and then solely focus on installing the full ROCm 1.6 stack as specified on its GitHub page.  Please follow these instructions:  

1. Uninstall amdgpu-pro and rocm (probably something like this:  sudo apt-get autoremove amdgpu-pro rocm rocm-dev rocm-libs)
2. Reboot
3. Go to the ROCm installation page and _solely_ follow those instructions (https://github.com/RadeonOpenCompute/ROCm#installing-from-amd-rocm-repositories)

Then, if you are still able to successfully run LeNet, please resolve this ticket.  Of course, if you notice another issue, please open a new ticket specifically for that.  

Best, 

Jeff

**Comment by BeamOfLight** [comment]
> Then, if you are still able to successfully run LeNet, please resolve this ticket.

With LeNet and `test_all.testbin --gtest_filter=GemmTest/0.TestGemmCPUGPU` - ok.

>  Of course, if you notice another issue, please open a new ticket specifically for that.

No problem
